// <auto-generated />
using System;
using FamilyCoordinationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyCoordinationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623223451_AddChoreSubtaskActor")]
    partial class AddChoreSubtaskActor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Category", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("HouseholdId", "CategoryId");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Chore", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChoreId"));

                    b.Property<DateOnly?>("AnchorDate")
                        .HasColumnType("date");

                    b.Property<int?>("AssigneeUserId")
                        .HasColumnType("integer");

                    b.Property<string>("AssignmentKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("None");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EffortPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("EffortTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EnteredByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastContributionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecurrenceMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RequiredCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("SnoozedUntil")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("HouseholdId", "ChoreId");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("EnteredByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("HouseholdId", "RoomId");

                    b.ToTable("Chores", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreCompletion", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<int>("CompletionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompletionId"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("EffortPointsSnapshot")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("HouseholdId", "ChoreId", "CompletionId");

                    b.HasIndex("CompletedByUserId");

                    b.ToTable("ChoreCompletions", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreEvent", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("HouseholdId", "ChoreId", "EventId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("ChoreEvents", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreParticipationEvent", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipationEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipationEventId"));

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubjectUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("HouseholdId", "ChoreId", "ParticipationEventId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("SubjectUserId");

                    b.HasIndex("HouseholdId", "ChoreId", "At");

                    b.ToTable("ChoreParticipationEvents", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreSubtask", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<int>("SubtaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubtaskId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("HouseholdId", "ChoreId", "SubtaskId");

                    b.ToTable("ChoreSubtasks", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("UserId");

                    b.HasIndex("IsRead", "IsResolved", "CreatedAt");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.HouseholdChoreDigestSettings", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Weekly");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SendDayOfWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SendHourLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(18);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookUrlProtected")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("HouseholdId");

                    b.ToTable("ChoreDigestSettings", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.HouseholdConnection", b =>
                {
                    b.Property<int>("HouseholdId1")
                        .HasColumnType("integer");

                    b.Property<int>("HouseholdId2")
                        .HasColumnType("integer");

                    b.Property<int?>("AcceptedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InitiatedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("HouseholdId1", "HouseholdId2");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("HouseholdId1");

                    b.HasIndex("HouseholdId2");

                    b.HasIndex("InitiatedByUserId");

                    b.ToTable("HouseholdConnections", null, t =>
                        {
                            t.HasCheckConstraint("CK_HouseholdConnections_OrderedIds", "\"HouseholdId1\" < \"HouseholdId2\"");
                        });
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.HouseholdInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsedByHouseholdId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsedByUserId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("UsedByHouseholdId");

                    b.HasIndex("UsedByUserId");

                    b.HasIndex("HouseholdId", "IsUsed", "ExpiresAt");

                    b.ToTable("HouseholdInvites", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.HouseholdRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.ToTable("HouseholdRequests", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.MealPlan", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("MealPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealPlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("HouseholdId", "MealPlanId");

                    b.ToTable("MealPlans", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.MealPlanEntry", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<string>("CustomMealName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("HouseholdId", "MealPlanId", "EntryId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("HouseholdId", "RecipeId");

                    b.ToTable("MealPlanEntries", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.Property<int?>("SharedFromHouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("SharedFromHouseholdName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SharedFromRecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("HouseholdId", "RecipeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SharedFromHouseholdId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("HouseholdId", "Name");

                    b.HasIndex("HouseholdId", "SharedFromHouseholdId");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.RecipeDraft", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HouseholdId", "UserId", "RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("RecipeDrafts");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("HouseholdId", "RecipeId", "IngredientId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Room", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("HouseholdId", "RoomId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ShoppingList", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShoppingListId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("MealPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("HouseholdId", "ShoppingListId");

                    b.HasIndex("HouseholdId", "MealPlanId");

                    b.ToTable("ShoppingLists", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ShoppingListItem", b =>
                {
                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsManuallyAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OriginalUnits")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("QuantityDelta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RecipeIngredientIds")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SourceRecipes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("HouseholdId", "ShoppingListId", "ItemId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("ShoppingListItems", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoresDefaultView")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWhitelisted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhysicalCapacityTier")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"GoogleId\" IS NOT NULL");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.UserFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "HouseholdId", "RecipeId");

                    b.HasIndex("HouseholdId", "RecipeId");

                    b.ToTable("UserFavorites", (string)null);
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Category", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Chore", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "EnteredBy")
                        .WithMany()
                        .HasForeignKey("EnteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "RoomId");

                    b.Navigation("Assignee");

                    b.Navigation("EnteredBy");

                    b.Navigation("Household");

                    b.Navigation("Owner");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreCompletion", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Chore", "Chore")
                        .WithMany("Completions")
                        .HasForeignKey("HouseholdId", "ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("CompletedBy");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreEvent", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "Target")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Chore", "Chore")
                        .WithMany("Events")
                        .HasForeignKey("HouseholdId", "ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Chore");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreParticipationEvent", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Chore", "Chore")
                        .WithMany("ParticipationEvents")
                        .HasForeignKey("HouseholdId", "ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Chore");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ChoreSubtask", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Chore", "Chore")
                        .WithMany("Subtasks")
                        .HasForeignKey("HouseholdId", "ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Feedback", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.HouseholdChoreDigestSettings", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.HouseholdConnection", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "AcceptedBy")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household1")
                        .WithMany()
                        .HasForeignKey("HouseholdId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household2")
                        .WithMany()
                        .HasForeignKey("HouseholdId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "InitiatedBy")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AcceptedBy");

                    b.Navigation("Household1");

                    b.Navigation("Household2");

                    b.Navigation("InitiatedBy");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.HouseholdInvite", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "UsedByHousehold")
                        .WithMany()
                        .HasForeignKey("UsedByHouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Household");

                    b.Navigation("UsedByHousehold");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.MealPlan", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany("MealPlans")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.MealPlanEntry", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.MealPlan", "MealPlan")
                        .WithMany("Entries")
                        .HasForeignKey("HouseholdId", "MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MealPlan");

                    b.Navigation("Recipe");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Recipe", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany("Recipes")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "SharedFromHousehold")
                        .WithMany()
                        .HasForeignKey("SharedFromHouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("Household");

                    b.Navigation("SharedFromHousehold");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.RecipeDraft", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("HouseholdId", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Room", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ShoppingList", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "MealPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyCoordinationApp.Data.Entities.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("HouseholdId", "ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("ShoppingList");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.User", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.UserFavorite", b =>
                {
                    b.HasOne("FamilyCoordinationApp.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyCoordinationApp.Data.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("HouseholdId", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Chore", b =>
                {
                    b.Navigation("Completions");

                    b.Navigation("Events");

                    b.Navigation("ParticipationEvents");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Household", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("Recipes");

                    b.Navigation("ShoppingLists");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.MealPlan", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FamilyCoordinationApp.Data.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
